### PR TITLE
Now using multi-ghc apt repositories for travis builds

### PR DESCRIPTION
**Pull request by solatis**
I am not sure if this will work; it is difficult for me to test. I'm hoping Travis picks up this pull request.

### CODE REVIEW

**Comment by solatis** [comment]
Ok, sorry for the noise, the pull request now does what we want it to do: test GHC 7.6, 7.8 and 7.10. It errors because of 7.10

**Comment by alpmestan** [comment]
That's great! Thanks a lot for taking care of this, again.

Want me to cut a new release with the 7.10-friendly change today?

**Comment by solatis** [comment]
That would be great. I think it should be a minor version update, since this is only a bugfix.

**Comment by alpmestan** [comment]
Yup. Merging the PR now -- expect a new release in a couple of minutes.

**Pull request merged**
